### ISSUE TITLE
Provide downloadable debug builds compiled  with address sanitizer

### ISSUE THREAD

**Issue by qarmin** [goostengine/goost#117]
Currently  due to lack of time and disk space I used prebuilt C# binaries.
When trying to execute https://github.com/qarmin/Qarminer I still have strange crashes with `ImageFrames.save_gif`, `_GoostImage.replace_color`, `ListNode` and `Mixin`, but I can't create proper reproduction project, because lack of using address sanitizer I can't find which exactly function cause problems.

**Comment by Xrayez** [comment]
I have enabled address and leak sanitizers in #110. Perhaps integrating https://github.com/qarmin/Qarminer in CI could be sufficient. Of course, build artifacts `linux-server` build could also be uploaded if we go this route:

https://github.com/goostengine/goost/blob/81110f08bf30640e263a2f7c100c16c8a2ffe3a4/.github/workflows/linux_builds.yml#L197-L267

But I'm not sure how this could affect GitHub Actions limited cache (which is 5 Gb per repository, AFAIK), on the other hand this might not affect cache if we only talk about providing build artifacts.

Another thing is that those builds are headless.

**Comment by Xrayez** [comment]
~~Regarding `ListNode` issue you mentioned, I opened a bug report #112, not sure how to fix unfortunately (might be engine issue).~~ figured there's a way at the end of the day, see #118.

**Comment by Xrayez** [comment]
@qarmin, so I've created a PR #119 which uploads those server debug builds, but it's roughly 248 Mb in download size, unpacked is 1.4 Gb... I think it may be worth to decrease the retention days for these builds due to this.

That said, would #119 be enough to help debugging those issues you mentioned?

**Comment by Xrayez** [comment]
Looks like you got it to try out according to #120, so merged now.

Server builds with sanitizers should be available to download via link at README as well.
