### ISSUE TITLE
Using ImageIndexed doesn't allow alpha values

### ISSUE THREAD

**Issue by 98teg** [goostengine/goost#5]
**Goost and Godot version:**
Godot: 3.2

**Issue description:**
I created an ImageIndexed with a texture with transparencies. When applying a palette, it doesn't show the correct alpha values anymore.

**Steps to reproduce:**
```
func load_land_tile(path : String):
    var image = ImageIndexed.new()
    
    image.load(path)
    image.convert(Image.FORMAT_RGBA8)
    
    if not image.has_palette():
        image.generate_palette(1)

    image.set_palette_color(0, Color.green)
    image.apply_palette()
```

**Comment by Xrayez** [comment]
> it doesn't show the correct alpha values anymore

Do you say that the alpha values are somewhere near zero but not completely zero?

Can you try this:
```gdscript
var with_alpha = true
image.generate_palette(1, ImageIndexed.DITHER_NONE, with_alpha)
```

**Comment by 98teg** [comment]
Now I see the problem. I needed to include an extra color in the palette for the transparent color. Thanks for the suggestion!

**Comment by Xrayez** [comment]
Yeah, when you think in `[0, 1]` range, it's easy to wrongly interpret that as 2 colors, especially if this has to do with palette size.
