### ISSUE TITLE
Compilation failed if the Godot repo already exists in the same folder as Goost

### ISSUE THREAD

**Issue by mbrlabs** [goostengine/goost#69]
**Goost and Godot version:**
gd3 f2ed253ddd12328ad93d14a99531442c099315fa

**OS/device including version:**
Manjaro Linux and Windows

**Issue description:**
I can't compile Goost. This is a Linux example but it looks similar on Windows. I'm using Python 3.9.1 and Scons 4.1.0:

```
scons: Reading SConscript files ...
Configuring Goost module ...
Building Godot with Goost ...
scons: Reading SConscript files ...
Automatically detected platform: linuxbsd
Build option 'custom_modules' must point to a directory with modules, not a single module.
CalledProcessError: Command '['scons', 'profile=/home/mbr/Projects/goost/modules/modules_config_gen.py', 'custom_modules=/home/mbr/Projects/goost', 'extra_suffix=goost']' returned non-zero exit status 255.:
  File "/home/mbr/Projects/goost/SConstruct", line 220:
    run(env.build_args, godot_dir.abspath)
  File "/home/mbr/Projects/goost/SConstruct", line 92:
    return subprocess.run(args, check=True, cwd=dir).returncode
  File "/usr/lib/python3.9/subprocess.py", line 524:
    raise CalledProcessError(retcode, process.args,
```

Here i'm in `/home/mbr/Projects/goost`. If i clone the project directly into my home directory it builds without problems.

**Steps to reproduce:**
Just follow the compile instructions in the Readme while beeing in a subdirectory of the home dir:
```
git clone https://github.com/goostengine/goost
cd goost
scons
```

**Comment by mbrlabs** [comment]
Ok, it's because i already cloned godot into that directory. So, not really a bug but maybe this can be detected and a more descriptive error message can be displayed?

**Comment by mbrlabs** [comment]
Hmm, weird though that godot gets cloned **into** the goost folder but if godot exists as **sibling** folder it fails.

**Comment by Xrayez** [comment]
> Ok, it's because i already cloned godot into that directory.

The error message regarding `custom_modules` looks like you're using an outdated version of Godot somewhere.

I've made several changes to Godot's module detection in 3.3: godotengine/godot#43057, godotengine/godot#46799, so the logic now requires Godot 3.3+. Goost does already try to detect minimum supported version in `SConstruct`, but the check won't work outside of Goost directory.

That said, this will be less of a problem in the future once all users shift towards compiling Godot 3.3/3.4 versions.

I'll test this anyways on Windows, maybe it's platform specific...

**Comment by mbrlabs** [comment]
Hmm, i have two versions of Godot in my `Projects` folder both of which are up to date with upstream:
- `godot3` which uses the 3.x branch
- `godot` which uses the master branch

I guess this would only work if `godot` would point to 3.3 instead of master?

**Comment by Xrayez** [comment]
I fail to reproduce the issue, but I think it's likely due to this:

https://github.com/goostengine/goost/blob/b4f3aac2fd0991d579406c2dfe57331991184368/SConstruct#L43

If I have `godot` in the parent directory which uses master branch, then I get a different error:
```
PS D:\usr\src\godotengine\godot\goost> scons
scons: Reading SConscript files ...
Configuring Goost module ...
Building Godot with Goost ...
scons: Reading SConscript files ...
Automatically detected platform: windows
Configuring for Windows: target=debug, bits=default
Found MSVC version 14.2, arch amd64, bits=64
Using custom build name: goost.Xrayez
ModuleNotFoundError: No module named 'compat':
  File "D:\usr\src\godotengine\godot\godot\SConstruct", line 675:
    SConscript("modules/SCsub")
  File "c:\users\xrayez\appdata\local\programs\python\python39\lib\site-packages\SCons\Script\SConscript.py", line 654:
    return method(*args, **kw)
  File "c:\users\xrayez\appdata\local\programs\python\python39\lib\site-packages\SCons\Script\SConscript.py", line 591:
    return _SConscript(self.fs, *files, **subst_kw)
  File "c:\users\xrayez\appdata\local\programs\python\python39\lib\site-packages\SCons\Script\SConscript.py", line 280:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "D:\usr\src\godotengine\godot\godot\modules\SCsub", line 46:
  File "c:\users\xrayez\appdata\local\programs\python\python39\lib\site-packages\SCons\Script\SConscript.py", line 654:
    return method(*args, **kw)
  File "c:\users\xrayez\appdata\local\programs\python\python39\lib\site-packages\SCons\Script\SConscript.py", line 591:
    return _SConscript(self.fs, *files, **subst_kw)
  File "c:\users\xrayez\appdata\local\programs\python\python39\lib\site-packages\SCons\Script\SConscript.py", line 280:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "D:\usr\src\godotengine\godot\goost\SCsub", line 7:
    from compat import isbasestring
", line 220:
    run(env.build_args, godot_dir.abspath)
  File "D:\usr\src\godotengine\godot\goost\SConstruct", line 90:
    return subprocess.run(args, check=True, shell=True, cwd=dir).returncode
  File "c:\users\xrayez\appdata\local\programs\python\python39\lib\subprocess.py", line 524:
    raise CalledProcessError(retcode, process.args,
```

So, if you remove:
https://github.com/goostengine/goost/blob/b4f3aac2fd0991d579406c2dfe57331991184368/SConstruct#L43

would it eliminate the issue for you? I think it's error-prone to rely on this logic anyways, so should be removed...

**Comment by mbrlabs** [comment]
Yes, removing that path (which points to my godot 4 branch) fixes it for me 👍
